export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
  modal,
}: {
  children: React.ReactNode,
  modal: React.ReactNode,
}) {
  return (
    <html lang="en">
      <body>
        {children && children}
        {modal && modal}
      </body>
    </html>
  )
}
